TorneoCO:
  seq_len:
    - 12
    - 24
    - step: 12
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 144    
TorneoNO2:
  seq_len:
    - 12
    - 24
    - step: 12
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 144
    
TorneoO3:
  seq_len:
    - 12
    - 24
    - step: 12
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 144
    
TorneoPM10:
  seq_len:
    - 12
    - 72
    - step: 12
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 144

Electricity:
  seq_len:
    - 4
    - 8
    - step: 4
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 96

ETTh1:
  seq_len:
    - 12
    - 24
    - step: 12
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 24

ETTh2:
  seq_len:
    - 12
    - 24
    - step: 12
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 24
    
ExchangeRate:
  seq_len:
    - 3
    - 7
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 3
    
Traffic:
  seq_len:
    - 3
    - 6
  pred_len:
    - 1
  select_timesteps:
    - True
  shift:
    - 24
    