NoSelection:
Linear:
  threshold: 
    - 0.5
    - 1.0
    - step: 0.05
Correlation:
  threshold: 
    - 0.5
    - 1.0
    - step: 0.05
MutualInformation:
  threshold: 
    - 0.5
    - 1.0
    - step: 0.05
TimeSelectionLayer:
  regularization: 
    - 0.00001
    - 0.0001
    - 0.001
